Implement smtp connection and handshake
metarhia/metamail pull request #8
Opened 2022-07-20 06:27 UTC by srg-kostyrko

- Implement smtp connection and handshake
- Organize response codes and errors
- Fallback to HELO if EHLO not supported
- Support secure connections and connection upgrade
- Add plain and login auth methods
- Add data sending
- Add error handling and connection close processing
- Add `run` command to ensure uninterrupted sequence of commands

- [x] tests and linter show no problems (`npm t`)
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [x] update .d.ts typings

Closes #4

2022-07-21 18:24 UTC, tshemsedinov requested changes

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-auth.js
> +  },
```suggestion
  LOGIN: (connection, auth) => connection.run(async () => {
    await connection.send(authLogin());
    await connection.send(authLoginUser(auth.user));
    await connection.send(authLoginPassword(auth.password));
  }) },
```

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-auth.js
> +}
```suggestion
const smptLogin = (connection, auth, supportedMethods) => {
  for (const methods of supportedMethods) {
    const runner = authMethods[methods];
    if (runner) return runner(connection, auth);
  }
  throw new Error('No supported auth methods');
};
```

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-codes.js
> +  ServiceNotAvaliable: '421',
I'd like to have keys in `lowerCamel` or `UPPER_SNAKE` here

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-commands.js
> +  );
```suggestion
  const credentials = `\u0000${user}\u0000${pass}`;
  const auth = Buffer.from(credentials, 'utf-8').toString('base64');
```

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-commands.js
> +  text: Buffer.from(password, 'utf-8').toString('base64'),
Code duplication, maybe we can extract this pattern as a function

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +  stream,
Maybe this can be placed in 1 line (max 80), try

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-error.js
> +module.exports = { SMTPError };
I'd to move SMTP error to `smtp-connection.js`

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +const LINE_REGEXP = /(\d{3})(-| )(.*)/i;
It's better to parse with string operations, we don't like regexps in codebase

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +function parseResponseLine(line) {
We prefer arrow functions averywhere

2022-07-21 18:24 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +  if (defaultHostname.match(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/)) {
It's better to check for IPv4 with https://nodejs.org/api/net.html#netisipv4input

2022-07-21 18:24 UTC, tshemsedinov commented on lib/transport.js
> +const smtp = (options) => new SMTPTransport(options);
Very small file

2022-07-22 11:29 UTC, srg-kostyrko commented
@tshemsedinov I addressed all the comments, please re-review

2022-08-09 16:47 UTC, tshemsedinov requested changes

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +    }
You can use one of the following techniques instead of writing promise to the property:
- Async lock example: https://github.com/HowProgrammingWorks/RaceCondition/blob/master/JavaScript/6-async-lock.js
- Here is use case for semaphore: https://github.com/metarhia/metautil/blob/master/test/semaphore.js

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +    }
```suggestion
    if (this.#currentSequence) await this.#currentSequence;
```

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +  async connect() {
Same case: use semaphore or locks

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +    plainSocket.removeListener('data', this.#onData);
Use `removeAllListeners`: https://nodejs.org/api/events.html#emitterremovealllistenerseventname

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +  };
Rename to `processChunk`

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +  };
Move to the place where callbacks applied to EE

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +  };
```suggestion
  const isMultiline = separator === MULTILINE_RESPONSE_SEPARATOR;
  return { code, isMultiline, data };
```

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +  getDefaultHostname,
```suggestion
  defaultHostname: getDefaultHostname(),
```

2022-08-09 16:47 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +  // IP should be enclosed in []
```suggestion
  const isFQDN = !defaultHostname || !defaultHostname.includes('.');
  if (isFQDN) return '[127.0.0.1]';
```

2022-08-09 16:47 UTC, tshemsedinov commented on metamail.d.ts
> +  };
```suggestion
  auth?: {
    user: string;
    password: string;
  };
```

2022-08-11 16:45 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +  #host = null;
```suggestion
  #host;
```

2022-08-11 16:45 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +  #destroyed = false;
`#active`

2022-08-11 16:45 UTC, tshemsedinov commented on lib/smtp/smtp-connection.js
> +    this.#dataBuffer += chunk;
- `this.#dataBuffer.push(chunk)`
- To get collected result `Buffer.concat(this.#dataBuffer).toString()`

2022-08-11 16:45 UTC, tshemsedinov commented on metamail.js
> +  ...require('./lib/smtp/smtp-transport'),
```suggestion
  ...require('./lib/smtp/smtp-transport.js'),
```

2022-08-16 16:30 UTC, tshemsedinov approved these changes

2022-08-16 16:30 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +class SMTPError extends Error {
```suggestion

class SMTPError extends Error {
```

2022-08-16 16:30 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +  let chunksBuffer = Buffer.from('');
```suggestion
  const chunks = [];
```

2022-08-16 16:30 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +    chunksBuffer = Buffer.concat([chunksBuffer, chunk]);
```suggestion
    chunks.push(chunk);
```

2022-08-16 16:30 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +    if (!bufferEndWith(chunksBuffer, SMTP_LINE_END)) continue;
```suggestion
    if (!bufferEndWith(chunk, SMTP_LINE_END)) continue;
```

2022-08-16 16:30 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +    const separator = readLastSeparator(chunksBuffer);
```suggestion
    const separator = readLastSeparator(chunk);
```

2022-08-16 16:30 UTC, tshemsedinov commented on lib/smtp/smtp-utils.js
> +    const { code, data } = parseResponseData(chunksBuffer.toString());
```suggestion
    const buffer = Buffer.concat(chunks);
    const { code, data } = parseResponseData(buffer.toString());
```

2022-08-16 16:36 UTC, merged